version: '1'
services:
  mysql:
    image: mysql:8.0
    networks:
      - jays_hanghae_network
    volumes:
      - ./db/conf.d:/etc/mysql/conf.d
      - ./db/data:/var/lib/mysql
    env_file: .env
    ports:
      - "3306:3306"
    environment:
      - TZ=Asia/Seoul
      - MYSQL_ROOT_PASSWORD=rootpassword
      - MYSQL_USER=mysqluser
      - MYSQL_PASSWORD=mysqlpw

  jay-hanghae-service:
    image: jays-hanghae:1.0.0
    networks:
      - jays_hanghae_network
    ports:
      - "8080:8080"
    depends_on:
      - mysql
    environment:
        - PROFILE=alpha

networks:
    jays_hanghae_network:
        driver: bridge
