jays:
    hanghae:
        journey:
            profile: local

spring:
    datasource:
        url: jdbc:mysql://mysql:3306/jays_hanghae
        username: root
        password: rootpassword
    jpa:
        hibernate:
            ddl-auto: update
