jays:
    hanghae:
        journey:
            profile: local

spring:
    datasource:
        url: jdbc:mysql://mysql:3306/jays_hanghae
        username: mysqluser
        password: mysqlpw
    jpa:
        hibernate:
            ddl-auto: update
